### PR TITLE
update css & searchbox text

### PR DESCRIPTION
**Pull request by lucays**
修改内容：

-  原主题在移动页面锚点跳转后锚点标题会被headers覆盖看不见，现在只在跳转的锚点上增加1行下移整块保证不被覆盖。参考了：https://stackoverflow.com/a/28824157
- 原主题正常来说，大标题间距2行，子标题间距1行。但子标题间如果以列表或note等提示框结尾，间距会从1行变成2行，就不统一了。把间距统一改成1行。
- 原主题行块无间距，如果用来写大段文字，会全凑在一起，加了1空行间距。（不是‘上边距'，写错了...）
- 搜索框的文字改成只用’Search'后，启用本地化后sphinx能自动翻译，zh_CN下会翻译成搜索。

### CODE REVIEW

**Comment by lepture** [comment]
CSS is compiled from assets. Please submit an issue at first, describe your issues with pictures.

**Comment by sloria** [comment]
FYI, I've proposed to make the search placeholder configurable in #6 .

**Comment by lucays** [comment]
> FYI, I've proposed to make the search placeholder configurable in #6 .

recently I found thead of table dont display in this theme, cause 
```
.head{
display:none;
}
```
I fixed it in my [forks](https://github.com/lucays/sphinx-typlog-theme).
add these code
```
 thead {
     color: #000;
     vertical-align: bottom;
     white-space: nowrap;
 }
 
  thead th.head {
     display: table-cell;
     position: inherit;
 }

 .wy-table-responsive {
     margin-bottom: 24px;
     max-width: 100%;
     overflow: auto;
 }
```
and modified
```
 .yue table[border] th {
     text-align: left;
     padding: 6px 8px 6px 10px;
     border: 1px solid #ddd
 }
```
to:
```
 .yue table[border] th {
      /* text-align: center; */
     white-space: nowrap;
     padding: 6px 8px 6px 10px;
     border: 1px solid #ddd
 }
```
them thead of table will display as sphinx-rtd-theme.

**Comment by lepture** [comment]
@lucays `.head` is now `.t-head`. So it will work.

**Comment by lucays** [comment]
> @lucays `.head` is now `.t-head`. So it will work.

I tried and yes it works.

**Pull request closed without merging**
